name: Android CI (Build from ZIP)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: List files for debugging
      - name: List files in root
        run: ls -la

      # Step 3: Unzip the project
      - name: Unzip LiMs_Project
        run: unzip LiMs_Project.zip -d LiMs_Project

      # Step 4: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 5: Set up Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # Step 6: Build APK
      - name: Build APK
        run: cd LiMs_Project && ./gradlew assembleDebug

      # Step 7: Upload APK artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: LiMs-APK
          path: LiMs_Project/app/build/outputs/apk/debug/app-debug.apk
