name: Android CI (Build LIMS APK)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Unzip project
        run: unzip -o LiMs_Project.zip -d LiMs_Project

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 33
          build-tools: 33.0.2

      - name: Find gradlew path
        id: find_gradlew
        run: |
          GRADLEW_PATH=$(find LiMs_Project -name gradlew -type f | head -n 1)
          if [ -z "$GRADLEW_PATH" ]; then
            echo "gradlew not found!"
            exit 1
          fi
          echo "gradlew path: $GRADLEW_PATH"
          echo "GRADLEW_PATH=$GRADLEW_PATH" >> $GITHUB_ENV

      - name: Make gradlew executable
        run: chmod +x $GRADLEW_PATH

      - name: Build APK
        run: $GRADLEW_PATH assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: LiMs-APK
          path: app/build/outputs/apk/debug/app-debug.apk
