name: Android CI (Build from ZIP)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Unzip project directly (avoids nested folder)
      - name: Unzip project
        run: unzip -o LiMs_Project.zip

      # 3️⃣ Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 4️⃣ Set up Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # 5️⃣ Build APK using Gradle wrapper
      - name: Build APK
        run: ./LiMs_Project/gradlew assembleDebug

      # 6️⃣ Upload APK artifact (v4, not deprecated)
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: LiMs-APK
          path: LiMs_Project/app/build/outputs/apk/debug/app-debug.apk
