name: Android CI (Build from ZIP)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Unzip project
        run: unzip LiMs_Project.zip -d LiMs_Project

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Build APK
        run: cd LiMs_Project && ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: LiMs-APK
          path: LiMs_Project/app/build/outputs/apk/debug/app-debug.apk
